<!-- ==============================================================================================================-->
<footer> 
	<br><br/>
		<a href="http://students.cpcc.edu/~lewing00" target="_blank">My Webspace</a> &#9553;
		<a href="https://www.linkedin.com/in/leeanna-ewing-3849b9167/" target="_blank">LinkedIn</a> &#9553;
		<a href="https://github.com/lewing00" target="_blank">Github</a> &#9553;
		<a href="https://lewing00.github.io/" target="_blank">Github Pages</a> &#9553;
		<a href="https://www.khanacademy.org/profile/lewing00" target="_blank">Khan Academy</a> &#9553;
		<a href="https://www.codecademy.com/lewing00" target="_blank">Codecademy</a> &#9553;
		<a href="https://www.freecodecamp.org/lewing00" target="_blank">freeCodeCamp</a> &#9553;
		<a href="https://jsfiddle.net/user/lewing00" target="_blank">JSFiddle</a> &#9553;
		<a href="https://profile.edx.org/u/lewing00" target="_blank">edX</a>	
	<br><br/>
		&copy;2019 Designed by <a href="mailto:lewing00@email.cpcc.edu">LeeAnna Ewing</a>
	<br><br/>
		<a href="http://validator.w3.org/check?uri=referer" style = "text-decoration: none"><img src="images/valid_html5.gif" alt="Validate HTML" /></a>
		<a href="http://jigsaw.w3.org/css-validator/check/referer" style = "text-decoration: none"><img src="images/vcss_blue.gif" alt="Validate CSS" /></a>
</footer>
<!-- ==============================================================================================================-->	
